// Mejorar vistas de GPS (1)/src/components/Devices.vue
<template>
  <div class="space-y-6">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
      <div>
        <h2 class="text-white mb-2">Dispositivos GPS</h2>
        <p class="text-neutral-400">{{ devices.length }} registrados</p>
      </div>
      
      <button
        @click="showDialog = true"
        class="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M5 12h14"/><path d="M12 5v14"/>
        </svg>
        Nuevo
      </button>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="bg-neutral-900 border border-neutral-800 hover:border-orange-500/50 transition-all rounded-lg p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-neutral-400 mb-1">Activos</p>
            <h3 class="text-white text-2xl">{{ activeDevices }}</h3>
          </div>
          <div class="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-500">
              <rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/>
            </svg>
          </div>
        </div>
      </div>

      <div class="bg-neutral-900 border border-neutral-800 hover:border-orange-500/50 transition-all rounded-lg p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-neutral-400 mb-1">Mantenimiento</p>
            <h3 class="text-white text-2xl">{{ inactiveDevices }}</h3>
          </div>
          <div class="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-500">
              <rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/>
            </svg>
          </div>
        </div>
      </div>
    </div>

    <!-- Filters -->
    <div class="bg-neutral-900 border border-neutral-800 rounded-lg p-6">
      <div class="flex flex-col md:flex-row gap-4">
        <input
          v-model="searchTerm"
          type="text"
          placeholder="Buscar..."
          class="flex-1 bg-black border border-neutral-800 text-white placeholder:text-neutral-400 px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none"
        />
        <select v-model="filterStatus" class="w-full md:w-[150px] bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg">
          <option>Todos</option>
          <option>Activo</option>
          <option>Inactivo</option>
        </select>
      </div>
    </div>

    <!-- Devices Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <div
        v-for="device in devices"
        :key="device.id"
        :class="[
          'bg-neutral-900 border border-neutral-800 hover:border-orange-500 transition-all rounded-lg p-6',
          device.highlighted ? 'ring-2 ring-orange-500/50' : ''
        ]"
      >
        <div class="flex items-start justify-between mb-4">
          <div class="flex items-center gap-3">
            <div class="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-500">
                <rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/>
              </svg>
            </div>
            <div>
              <h4 class="text-white mb-1">{{ device.name }}</h4>
              <span
                :class="[
                  'inline-flex px-2 py-1 rounded text-xs',
                  device.status === 'Activo' ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400'
                ]"
              >
                {{ device.status }}
              </span>
            </div>
          </div>
        </div>

        <div class="space-y-2 text-sm text-neutral-400 mb-4">
          <p>{{ device.imei }}</p>
          <p>{{ device.brand }}</p>
          <p>{{ device.owner }}</p>
          <p>{{ device.registrationDate }}</p>
        </div>

        <div class="flex gap-2 pt-4 border-t border-neutral-800">
          <button class="flex-1 bg-neutral-800 text-white hover:bg-orange-500 p-2 rounded-lg transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>
            </svg>
          </button>
          <button class="flex-1 bg-neutral-800 text-white hover:bg-orange-500 p-2 rounded-lg transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/><path d="m15 5 4 4"/>
            </svg>
          </button>
          <button class="flex-1 bg-neutral-800 text-red-400 hover:bg-red-500/10 p-2 rounded-lg transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>
            </svg>
          </button>
        </div>
      </div>
    </div>

    <!-- Dialog -->
    <Teleport to="body">
      <Transition name="modal">
        <div v-if="showDialog" class="fixed inset-0 z-50 flex items-center justify-center">
          <div class="absolute inset-0 bg-black/50" @click="showDialog = false" />
          <div class="relative bg-neutral-900 border border-neutral-800 rounded-lg p-6 w-full max-w-md mx-4">
            <h3 class="text-white mb-4">Registrar Nuevo Dispositivo</h3>
            <div class="space-y-4">
              <input type="text" placeholder="Nombre del dispositivo" class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none" />
              <input type="text" placeholder="IMEI" class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none" />
              <input type="text" placeholder="Marca" class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none" />
              <select class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none">
                <option>Seleccionar usuario</option>
                <option>Juan Pérez</option>
                <option>María García</option>
              </select>
            </div>
            <div class="flex gap-2 mt-6">
              <button @click="showDialog = false" class="flex-1 bg-neutral-800 text-white px-4 py-2 rounded-lg hover:bg-neutral-700 transition-colors">
                Cancelar
              </button>
              <button @click="showDialog = false" class="flex-1 bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg transition-colors">
                Registrar
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

interface Device {
  id: string;
  name: string;
  imei: string;
  brand: string;
  owner: string;
  registrationDate: string;
  status: string;
  highlighted?: boolean;
}

const searchTerm = ref('');
const filterStatus = ref('Todos');
const showDialog = ref(false);

const devices = ref<Device[]>([
  {
    id: '1',
    name: 'GPS Tracker Proaztazd',
    imei: 'IMEI: 123456789012345',
    brand: 'Marca: TechGPS',
    owner: 'Juan Pérez',
    registrationDate: '17/11/2025',
    status: 'Activo',
    highlighted: true
  },
  {
    id: '2',
    name: 'GPS Tracker Lite',
    imei: 'IMEI: 987654321098765',
    brand: 'Marca: TechGPS',
    owner: 'Juan Pérez',
    registrationDate: '17/11/2025',
    status: 'Activo'
  },
  {
    id: '3',
    name: 'GPS Tracker Pro',
    imei: 'IMEI: 188380741960220',
    brand: 'Marca: TechGPS',
    owner: 'Juan Pérez',
    registrationDate: '12/11/2025',
    status: 'Inactivo'
  },
  {
    id: '4',
    name: 'zzzamsing',
    imei: 'IMEI: 123456789001',
    brand: 'Marca: samsung',
    owner: 'napdoll',
    registrationDate: '26/11/2025',
    status: 'Activo'
  }
]);

const activeDevices = computed(() => devices.value.filter(d => d.status === 'Activo').length);
const inactiveDevices = computed(() => devices.value.filter(d => d.status === 'Inactivo').length);
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
</style>

// Mejorar vistas de GPS (1)/src/components/Devices.tsx
import { useState } from "react";
import { motion } from "motion/react";
import { Card, CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "./ui/dialog";
import { Smartphone, MapPin, Edit, Trash2, Plus, Search } from "lucide-react";

interface DeviceType {
  id: string;
  name: string;
  imei: string;
  brand: string;
  owner: string;
  registrationDate: string;
  status: "Activo" | "Inactivo";
  highlighted?: boolean;
}

const mockDevices: DeviceType[] = [
  {
    id: "1",
    name: "GPS Tracker Proaztazd",
    imei: "IMEI: 123456789012345",
    brand: "Marca: TechGPS",
    owner: "Juan Pérez",
    registrationDate: "17/11/2025",
    status: "Activo",
    highlighted: true
  },
  {
    id: "2",
    name: "GPS Tracker Lite",
    imei: "IMEI: 987654321098765",
    brand: "Marca: TechGPS",
    owner: "Juan Pérez",
    registrationDate: "17/11/2025",
    status: "Activo"
  },
  {
    id: "3",
    name: "GPS Tracker Pro",
    imei: "IMEI: 188380741960220",
    brand: "Marca: TechGPS",
    owner: "Juan Pérez",
    registrationDate: "12/11/2025",
    status: "Inactivo"
  },
  {
    id: "4",
    name: "zzzamsing",
    imei: "IMEI: 123456789001",
    brand: "Marca: samsung",
    owner: "napdoll",
    registrationDate: "26/11/2025",
    status: "Activo"
  }
];

export function Devices() {
  const [devices] = useState<DeviceType[]>(mockDevices);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterStatus, setFilterStatus] = useState("Todos");

  const activeDevices = devices.filter(d => d.status === "Activo").length;
  const inactiveDevices = devices.filter(d => d.status === "Inactivo").length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-white mb-2">Dispositivos GPS</h2>
          <p className="text-neutral-400">{devices.length} registrados</p>
        </div>
        
        <Dialog>
          <DialogTrigger asChild>
            <Button className="bg-orange-500 hover:bg-orange-600 text-white">
              <Plus className="mr-2 h-4 w-4" />
              Nuevo
            </Button>
          </DialogTrigger>
          <DialogContent className="bg-neutral-900 border-neutral-800 text-white">
            <DialogHeader>
              <DialogTitle>Registrar Nuevo Dispositivo</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div>
                <label className="text-neutral-400 mb-2 block">Nombre del dispositivo</label>
                <Input 
                  placeholder="Ej: GPS Tracker 01"
                  className="bg-black border-neutral-800 text-white"
                />
              </div>
              <div>
                <label className="text-neutral-400 mb-2 block">IMEI</label>
                <Input 
                  placeholder="123456789012345"
                  className="bg-black border-neutral-800 text-white"
                />
              </div>
              <div>
                <label className="text-neutral-400 mb-2 block">Marca</label>
                <Input 
                  placeholder="Ej: TechGPS"
                  className="bg-black border-neutral-800 text-white"
                />
              </div>
              <div>
                <label className="text-neutral-400 mb-2 block">Propietario</label>
                <Select>
                  <SelectTrigger className="bg-black border-neutral-800 text-white">
                    <SelectValue placeholder="Seleccionar usuario" />
                  </SelectTrigger>
                  <SelectContent className="bg-neutral-900 border-neutral-800">
                    <SelectItem value="1">Juan Pérez</SelectItem>
                    <SelectItem value="2">María García</SelectItem>
                    <SelectItem value="3">Carlos López</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="flex gap-2">
              <Button className="flex-1 bg-orange-500 hover:bg-orange-600 text-white">
                Registrar Dispositivo
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="bg-neutral-900 border-neutral-800 hover:border-orange-500/50 transition-all">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-neutral-400 mb-1">Activos</p>
                  <h3 className="text-white">{activeDevices}</h3>
                </div>
                <div className="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
                  <Smartphone className="h-6 w-6 text-orange-500" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          <Card className="bg-neutral-900 border-neutral-800 hover:border-orange-500/50 transition-all">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-neutral-400 mb-1">Mantenimiento</p>
                  <h3 className="text-white">{inactiveDevices}</h3>
                </div>
                <div className="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
                  <Smartphone className="h-6 w-6 text-orange-500" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      {/* Filters */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <Card className="bg-neutral-900 border-neutral-800">
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-neutral-400" />
                <Input
                  placeholder="Buscar..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="bg-black border-neutral-800 text-white placeholder:text-neutral-400 pl-10"
                />
              </div>
              
              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-full md:w-[150px] bg-black border-neutral-800 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-neutral-900 border-neutral-800">
                  <SelectItem value="Todos">Todos</SelectItem>
                  <SelectItem value="Activo">Activo</SelectItem>
                  <SelectItem value="Inactivo">Inactivo</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Devices Grid */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
      >
        {devices.map((device, index) => (
          <Card 
            key={device.id} 
            className={`bg-neutral-900 border-neutral-800 hover:border-orange-500 transition-all ${
              device.highlighted ? 'ring-2 ring-orange-500/50' : ''
            }`}
          >
            <CardContent className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
                    <Smartphone className="h-6 w-6 text-orange-500" />
                  </div>
                  <div>
                    <h4 className="text-white mb-1">{device.name}</h4>
                    <Badge 
                      className={`${
                        device.status === "Activo" 
                          ? "bg-green-500/20 text-green-400 border-green-500/30" 
                          : "bg-red-500/20 text-red-400 border-red-500/30"
                      }`}
                    >
                      {device.status}
                    </Badge>
                  </div>
                </div>
              </div>

              <div className="space-y-2 text-sm text-neutral-400 mb-4">
                <p>{device.imei}</p>
                <p>{device.brand}</p>
                <p>{device.owner}</p>
                <p>{device.registrationDate}</p>
              </div>

              <div className="flex gap-2 pt-4 border-t border-neutral-800">
                <Button
                  size="icon"
                  variant="ghost"
                  className="flex-1 bg-neutral-800 text-white hover:bg-orange-500"
                >
                  <MapPin className="h-4 w-4" />
                </Button>
                <Button
                  size="icon"
                  variant="ghost"
                  className="flex-1 bg-neutral-800 text-white hover:bg-orange-500"
                >
                  <Edit className="h-4 w-4" />
                </Button>
                <Button
                  size="icon"
                  variant="ghost"
                  className="flex-1 bg-neutral-800 text-red-400 hover:bg-red-500/10"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </motion.div>
    </div>
  );
}
