// Mejorar vistas de GPS (1)/src/components/Users.tsx
import { useState } from "react";
import { motion } from "motion/react";
import { Card, CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "./ui/dialog";
import { User, Mail, Edit, Trash2, UserPlus, Search, ShieldCheck } from "lucide-react";

interface UserType {
  id: string;
  name: string;
  email: string;
  role: "Administrador" | "Empleado";
  status: "Activo" | "Inactivo";
  deviceId: string;
  lastActivity: string;
}

const mockUsers: UserType[] = [
  {
    id: "1",
    name: "Administrador",
    email: "admin@regps.com",
    role: "Administrador",
    status: "Activo",
    deviceId: "#ID: #1",
    lastActivity: "Sin actividad reciente"
  },
  {
    id: "2",
    name: "Juan",
    email: "juan@regps.com",
    role: "Empleado",
    status: "Activo",
    deviceId: "#ID: #2",
    lastActivity: "Sin actividad reciente"
  },
  {
    id: "3",
    name: "María",
    email: "maria@regps.com",
    role: "Empleado",
    status: "Activo",
    deviceId: "#ID: #3",
    lastActivity: "Sin actividad reciente"
  }
];

export function Users() {
  const [users] = useState<UserType[]>(mockUsers);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterRole, setFilterRole] = useState("Todos");
  const [filterStatus, setFilterStatus] = useState("Estado");

  const activeUsers = users.filter(u => u.status === "Activo").length;
  const adminUsers = users.filter(u => u.role === "Administrador").length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-white mb-2">Usuarios</h2>
          <p className="text-neutral-400">{users.length} registros</p>
        </div>
        
        <Dialog>
          <DialogTrigger asChild>
            <Button className="bg-orange-500 hover:bg-orange-600 text-white">
              <UserPlus className="mr-2 h-4 w-4" />
              Nuevo
            </Button>
          </DialogTrigger>
          <DialogContent className="bg-neutral-900 border-neutral-800 text-white">
            <DialogHeader>
              <DialogTitle>Crear Nuevo Usuario</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div>
                <label className="text-neutral-400 mb-2 block">Nombre</label>
                <Input 
                  placeholder="Nombre completo"
                  className="bg-black border-neutral-800 text-white"
                />
              </div>
              <div>
                <label className="text-neutral-400 mb-2 block">Email</label>
                <Input 
                  type="email"
                  placeholder="usuario@email.com"
                  className="bg-black border-neutral-800 text-white"
                />
              </div>
              <div>
                <label className="text-neutral-400 mb-2 block">Rol</label>
                <Select defaultValue="Empleado">
                  <SelectTrigger className="bg-black border-neutral-800 text-white">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-neutral-900 border-neutral-800">
                    <SelectItem value="Administrador">Administrador</SelectItem>
                    <SelectItem value="Empleado">Empleado</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="text-neutral-400 mb-2 block">Contraseña</label>
                <Input 
                  type="password"
                  placeholder="••••••••"
                  className="bg-black border-neutral-800 text-white"
                />
              </div>
            </div>
            <div className="flex gap-2">
              <Button className="flex-1 bg-orange-500 hover:bg-orange-600 text-white">
                Crear Usuario
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="bg-neutral-900 border-neutral-800 hover:border-orange-500/50 transition-all">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-neutral-400 mb-1">Activos</p>
                  <h3 className="text-white">{activeUsers}</h3>
                </div>
                <div className="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
                  <User className="h-6 w-6 text-orange-500" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
        >
          <Card className="bg-neutral-900 border-neutral-800 hover:border-orange-500/50 transition-all">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-neutral-400 mb-1">Admins</p>
                  <h3 className="text-white">{adminUsers}</h3>
                </div>
                <div className="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
                  <ShieldCheck className="h-6 w-6 text-orange-500" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      {/* Filters */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <Card className="bg-neutral-900 border-neutral-800">
          <CardContent className="p-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-neutral-400" />
                <Input
                  placeholder="Buscar..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="bg-black border-neutral-800 text-white placeholder:text-neutral-400 pl-10"
                />
              </div>
              
              <Select value={filterRole} onValueChange={setFilterRole}>
                <SelectTrigger className="w-full md:w-[150px] bg-black border-neutral-800 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-neutral-900 border-neutral-800">
                  <SelectItem value="Todos">Todos</SelectItem>
                  <SelectItem value="Administrador">Administrador</SelectItem>
                  <SelectItem value="Empleado">Empleado</SelectItem>
                </SelectContent>
              </Select>

              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-full md:w-[150px] bg-black border-neutral-800 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-neutral-900 border-neutral-800">
                  <SelectItem value="Estado">Estado</SelectItem>
                  <SelectItem value="Activo">Activo</SelectItem>
                  <SelectItem value="Inactivo">Inactivo</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Users List */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="space-y-3"
      >
        {users.map((user, index) => (
          <Card 
            key={user.id} 
            className="bg-neutral-900 border-neutral-800 hover:border-orange-500 transition-all cursor-pointer"
          >
            <CardContent className="p-6">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="flex items-center gap-4 flex-1">
                  <div className="h-12 w-12 rounded-full bg-orange-500/10 flex items-center justify-center">
                    <User className="h-6 w-6 text-orange-500" />
                  </div>
                  
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <h4 className="text-white">{user.name}</h4>
                      <Badge 
                        className={`${
                          user.role === "Administrador" 
                            ? "bg-orange-500/20 text-orange-400 border-orange-500/30" 
                            : "bg-green-500/20 text-green-400 border-green-500/30"
                        }`}
                      >
                        {user.role}
                      </Badge>
                      <Badge 
                        className={`${
                          user.status === "Activo" 
                            ? "bg-green-500/20 text-green-400 border-green-500/30" 
                            : "bg-neutral-600/20 text-neutral-400 border-neutral-600/30"
                        }`}
                      >
                        {user.status}
                      </Badge>
                    </div>
                    
                    <div className="flex flex-col gap-1 text-sm text-neutral-400">
                      <div className="flex items-center gap-2">
                        <Mail className="h-4 w-4" />
                        <span>{user.email}</span>
                      </div>
                      <div className="flex items-center gap-4">
                        <span>{user.deviceId}</span>
                        <span>•</span>
                        <span>{user.lastActivity}</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="flex gap-2">
                  <Button
                    size="icon"
                    variant="ghost"
                    className="rounded-full bg-neutral-800 text-white hover:bg-orange-500"
                  >
                    <Edit className="h-4 w-4" />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="rounded-full bg-neutral-800 text-white hover:bg-orange-500"
                  >
                    <ShieldCheck className="h-4 w-4" />
                  </Button>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="rounded-full bg-neutral-800 text-red-400 hover:bg-red-500/10"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </motion.div>
    </div>
  );
}

// Mejorar vistas de GPS (1)/src/components/Users.vue
<template>
  <div class="space-y-6">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
      <div>
        <h2 class="text-white mb-2">Usuarios</h2>
        <p class="text-neutral-400">{{ users.length }} registros</p>
      </div>
      
      <button
        @click="showDialog = true"
        class="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/>
        </svg>
        Nuevo
      </button>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="bg-neutral-900 border border-neutral-800 hover:border-orange-500/50 transition-all rounded-lg p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-neutral-400 mb-1">Activos</p>
            <h3 class="text-white text-2xl">{{ activeUsers }}</h3>
          </div>
          <div class="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-500">
              <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>
            </svg>
          </div>
        </div>
      </div>

      <div class="bg-neutral-900 border border-neutral-800 hover:border-orange-500/50 transition-all rounded-lg p-6">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-neutral-400 mb-1">Admins</p>
            <h3 class="text-white text-2xl">{{ adminUsers }}</h3>
          </div>
          <div class="h-12 w-12 rounded-xl bg-orange-500/10 flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-500">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/><path d="m9 12 2 2 4-4"/>
            </svg>
          </div>
        </div>
      </div>
    </div>

    <!-- Filters -->
    <div class="bg-neutral-900 border border-neutral-800 rounded-lg p-6">
      <div class="flex flex-col md:flex-row gap-4">
        <input
          v-model="searchTerm"
          type="text"
          placeholder="Buscar..."
          class="flex-1 bg-black border border-neutral-800 text-white placeholder:text-neutral-400 px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none"
        />
        <select v-model="filterRole" class="w-full md:w-[150px] bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg">
          <option>Todos</option>
          <option>Administrador</option>
          <option>Empleado</option>
        </select>
      </div>
    </div>

    <!-- Users List -->
    <div class="space-y-3">
      <div
        v-for="user in users"
        :key="user.id"
        class="bg-neutral-900 border border-neutral-800 hover:border-orange-500 transition-all cursor-pointer rounded-lg p-6"
      >
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div class="flex items-center gap-4 flex-1">
            <div class="h-12 w-12 rounded-full bg-orange-500/10 flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-orange-500">
                <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>
              </svg>
            </div>
            
            <div class="flex-1">
              <div class="flex items-center gap-2 mb-2">
                <h4 class="text-white">{{ user.name }}</h4>
                <span :class="['inline-flex px-2 py-1 rounded text-xs', user.role === 'Administrador' ? 'bg-orange-500/20 text-orange-400' : 'bg-green-500/20 text-green-400']">
                  {{ user.role }}
                </span>
                <span :class="['inline-flex px-2 py-1 rounded text-xs', user.status === 'Activo' ? 'bg-green-500/20 text-green-400' : 'bg-neutral-600/20 text-neutral-400']">
                  {{ user.status }}
                </span>
              </div>
              
              <div class="flex flex-col gap-1 text-sm text-neutral-400">
                <span>{{ user.email }}</span>
                <span>{{ user.deviceId }}</span>
              </div>
            </div>
          </div>

          <div class="flex gap-2">
            <button class="bg-neutral-800 text-white hover:bg-orange-500 p-2 rounded-lg transition-colors">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/><path d="m15 5 4 4"/>
              </svg>
            </button>
            <button class="bg-neutral-800 text-red-400 hover:bg-red-500/10 p-2 rounded-lg transition-colors">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Dialog -->
    <Teleport to="body">
      <Transition name="modal">
        <div v-if="showDialog" class="fixed inset-0 z-50 flex items-center justify-center">
          <div class="absolute inset-0 bg-black/50" @click="showDialog = false" />
          <div class="relative bg-neutral-900 border border-neutral-800 rounded-lg p-6 w-full max-w-md mx-4">
            <h3 class="text-white mb-4">Crear Nuevo Usuario</h3>
            <div class="space-y-4">
              <input type="text" placeholder="Nombre completo" class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none" />
              <input type="email" placeholder="usuario@email.com" class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none" />
              <select class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none">
                <option>Administrador</option>
                <option>Empleado</option>
              </select>
              <input type="password" placeholder="••••••••" class="w-full bg-black border border-neutral-800 text-white px-4 py-2 rounded-lg focus:border-orange-500 focus:outline-none" />
            </div>
            <div class="flex gap-2 mt-6">
              <button @click="showDialog = false" class="flex-1 bg-neutral-800 text-white px-4 py-2 rounded-lg hover:bg-neutral-700 transition-colors">
                Cancelar
              </button>
              <button @click="showDialog = false" class="flex-1 bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded-lg transition-colors">
                Crear Usuario
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  status: string;
  deviceId: string;
}

const searchTerm = ref('');
const filterRole = ref('Todos');
const showDialog = ref(false);

const users = ref<User[]>([
  {
    id: '1',
    name: 'Administrador',
    email: 'admin@regps.com',
    role: 'Administrador',
    status: 'Activo',
    deviceId: '#ID: #1'
  },
  {
    id: '2',
    name: 'Juan',
    email: 'juan@regps.com',
    role: 'Empleado',
    status: 'Activo',
    deviceId: '#ID: #2'
  },
  {
    id: '3',
    name: 'María',
    email: 'maria@regps.com',
    role: 'Empleado',
    status: 'Activo',
    deviceId: '#ID: #3'
  }
]);

const activeUsers = computed(() => users.value.filter(u => u.status === 'Activo').length);
const adminUsers = computed(() => users.value.filter(u => u.role === 'Administrador').length);
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}
</style>
