// Mejorar vistas de GPS (1)/src/App.tsx
import { useState } from 'react';
import { Dashboard } from './components/Dashboard';
import { RouteHistory } from './components/RouteHistory';
import { Geofencing } from './components/Geofencing';
import { Alerts } from './components/Alerts';
import { Users } from './components/Users';
import { Devices } from './components/Devices';
import { Navbar } from './components/Navbar';
import { Footer } from './components/Footer';

export default function App() {
  const [activeView, setActiveView] = useState('dashboard');

  const renderView = () => {
    switch (activeView) {
      case 'dashboard':
        return <Dashboard />;
      case 'routes':
        return <RouteHistory />;
      case 'geofencing':
        return <Geofencing />;
      case 'alerts':
        return <Alerts />;
      case 'users':
        return <Users />;
      case 'devices':
        return <Devices />;
      default:
        return <Dashboard />;
    }
  };

  return (
    <div className="min-h-screen bg-black flex flex-col">
      <Navbar activeView={activeView} onViewChange={setActiveView} />
      
      <div className="container mx-auto p-4 md:p-6 lg:p-8 flex-1">
        {renderView()}
      </div>

      <Footer />
    </div>
  );
}

// Mejorar vistas de GPS (1)/src/App.vue
<template>
  <div class="min-h-screen bg-black flex flex-col">
    <Navbar :activeView="activeView" @view-change="setActiveView" />
    
    <div class="container mx-auto p-4 md:p-6 lg:p-8 flex-1">
      <component :is="currentViewComponent" />
    </div>

    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import Navbar from './components/Navbar.vue';
import Footer from './components/Footer.vue';
import Dashboard from './components/Dashboard.vue';
import RouteHistory from './components/RouteHistory.vue';
import Geofencing from './components/Geofencing.vue';
import Alerts from './components/Alerts.vue';
import Users from './components/Users.vue';
import Devices from './components/Devices.vue';

const activeView = ref('dashboard');

const viewComponents = {
  dashboard: Dashboard,
  routes: RouteHistory,
  geofencing: Geofencing,
  alerts: Alerts,
  users: Users,
  devices: Devices,
};

const currentViewComponent = computed(() => {
  return viewComponents[activeView.value as keyof typeof viewComponents] || Dashboard;
});

const setActiveView = (view: string) => {
  activeView.value = view;
};
</script>
